# Generated by Django 2.2.5 on 2019-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('activity_time', models.DateTimeField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
