# Generated by Django 2.2.5 on 2019-10-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='activity_time',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='slug',
        ),
    ]
